taskcluster/taskcluster-web

package.json, src/components/Query/index.jsx, src/components/Spinner/index.jsx, src/components/TaskDetailsCard/index.jsx, src/components/TaskRunsCard/index.jsx, src/fragments/artifacts.graphql, src/theme.js, src/utils.js, src/utils/constants.js, src/utils/labels.js, src/views/Tasks/ViewTask/index.jsx, src/views/Tasks/ViewTask/pageArtifacts.graphql, src/views/Tasks/ViewTask/task.graphql, yarn.lock
=> Add artifacts list to task runs

.neutrinorc.js, src/components/ConnectionDataTable/index.jsx, src/components/TaskRunsCard/index.jsx, src/theme.js
=> Extract artifacts table into generic connection data table

src/components/Log/index.jsx, src/views/Tasks/LiveTaskLog/index.jsx, src/views/Tasks/TaskLog/index.jsx
=> Link to external raw log from log views

package.json, src/App/routes.jsx, src/components/AwsProvisionerHealthTable/index.jsx, src/components/Dashboard/SidebarList.jsx, src/utils/prop-types.js, src/views/AwsProvisioner/ViewAwsHealth/awsHealth.graphql, src/views/AwsProvisioner/ViewAwsHealth/index.jsx, src/views/AwsProvisioner/index.jsx, yarn.lock
Resolves https://github.com/taskcluster/taskcluster-web/issues/32.
=> AWS provisioner health view

src/App/routes.jsx, src/components/SecretsTable/index.jsx, src/utils/constants.js, src/utils/prop-types.js, src/views/Secrets/ViewSecrets/index.jsx, src/views/Secrets/ViewSecrets/secrets.graphql, src/views/Secrets/index.jsx
=> Create Secret list view

src/components/ClientForm/index.jsx, src/components/HookForm/index.jsx, src/components/RoleForm/index.jsx, src/theme.js, src/views/CachePurges/CreatePurgeCacheRequest/index.jsx, src/views/CachePurges/index.jsx
=> Create purge cache request view

package.json, src/App/routes.jsx, src/components/ErrorPanel/index.jsx, src/views/Quickstart/github.graphql, src/views/Quickstart/index.jsx, yarn.lock
=> Add Quickstart view

src/App/routes.jsx, src/components/CodeEditor/index.jsx, src/components/Dashboard/SidebarList.jsx, src/views/Scopes/ListScopes/index.jsx, src/views/Scopes/index.jsx, src/views/ScopesetExpander/index.jsx, src/views/ScopesetExpander/scopeset.graphql
=> Add Scopeset Expander

package.json, src/utils/constants.js, src/utils/db.js, src/utils/getTaskIdHistory.js, src/views/Tasks/NoTask/RecentTasks.jsx, src/views/Tasks/NoTask/index.jsx, src/views/Tasks/NoTask/recentTask.graphql, src/views/Tasks/ViewTask/index.jsx, yarn.lock
=> Add recent tasks to /tasks

.gitignore, src/components/ClientForm/index.jsx, src/components/HookForm/index.jsx, src/components/SpeedDialAction/index.jsx, src/views/AwsProvisioner/ViewWorkerTypes/index.jsx, src/views/Provisioners/ViewWorker/index.jsx, src/views/Provisioners/ViewWorkers/index.jsx
Relates to https://github.com/taskcluster/taskcluster-web/issues/64.
=> Augment SpeedDialAction with auth

src/components/SecretForm/index.jsx, src/components/SecretsTable/index.jsx, src/utils/prop-types.js, src/views/Secrets/ViewSecret/createSecret.graphql, src/views/Secrets/ViewSecret/deleteSecret.graphql, src/views/Secrets/ViewSecret/index.jsx, src/views/Secrets/ViewSecret/secret.graphql, src/views/Secrets/ViewSecret/updateSecret.graphql, src/views/Secrets/index.jsx
=> Add create/edit secret view

src/components/AwsProvisionerWorkerTypeTable/index.jsx, src/components/AwsRecentErrorsTable/index.jsx, src/utils/prop-types.js, src/views/AwsProvisioner/ViewRecentErrors/index.jsx, src/views/AwsProvisioner/ViewRecentErrors/recentErrors.graphql, src/views/AwsProvisioner/ViewWorkerTypes/index.jsx, src/views/AwsProvisioner/index.jsx
=> Add AWS recent errors view

src/App/routes.jsx, src/components/Dashboard/UserMenu.jsx, src/views/Profile/index.jsx, src/views/Profile/profile.graphql
This adds the credential information view under `/profile`. In the future, we can add more stuff to that view.
Resolves #48.
=> Add profile page (credentials view)

package.json, yarn.lock
Reverts taskcluster/taskcluster-web#120
=> Revert "Update packages"

package.json, src/App/Main.jsx, src/components/Dashboard/SidebarListItem.jsx, src/components/IndexNamespacesTable/index.jsx, src/components/IndexTaskNamespaceTable/index.jsx, src/components/IndexedEntry/index.jsx, src/components/JsonInspector/index.jsx, src/utils/buildArtifactUrl.js, src/utils/constants.js, src/utils/getIconFromMime.js, src/utils/prop-types.js, src/utils/urls.js, src/views/Tasks/TaskIndex/IndexedTask/artifacts.graphql, src/views/Tasks/TaskIndex/IndexedTask/index.jsx, src/views/Tasks/TaskIndex/IndexedTask/indexedTask.graphql, src/views/Tasks/TaskIndex/ListNamespaces/index.jsx, src/views/Tasks/TaskIndex/ListNamespaces/namespaces.graphql, src/views/Tasks/TaskIndex/index.jsx, src/views/Tasks/TaskIndex/taskNamespace.graphql, src/views/Tasks/index.jsx, yarn.lock
Resolves https://github.com/taskcluster/taskcluster-web/issues/43.
=> Add task index view

src/components/AwsProvisionerWorkerTypeTable/index.jsx, src/components/CachePurgesTable/index.jsx, src/components/ClientScopesTable/index.jsx, src/components/ClientsTable/index.jsx, src/components/IndexTaskNamespaceTable/index.jsx, src/components/RoleScopesTable/index.jsx, src/components/RolesTable/index.jsx, src/components/SecretsTable/index.jsx, src/components/WorkerTable/index.jsx, src/components/WorkerTypesTable/index.jsx, src/components/WorkersTable/index.jsx
Replaced memoizeWith function with memoize in all places. 
Resolves  #90.
=> Remove ramda's memoize function and use fast-memoize (#90)

package.json, yarn.lock
Updated component module to updated version to fix #127.
=> Update component module to updated version (#127)

src/components/Dashboard/index.jsx
=> Add view help section prop to the Dashboard component

src/App/routes.jsx, src/components/HelpView/index.jsx, src/views/AwsProvisioner/ViewWorkerTypes/index.jsx, src/views/AwsProvisioner/index.jsx, src/views/CachePurges/ViewCachePurges/index.jsx, src/views/CachePurges/index.jsx, src/views/Clients/ViewClients/index.jsx, src/views/Clients/index.jsx, src/views/Hooks/ListHooks/index.jsx, src/views/Hooks/index.jsx, src/views/Provisioners/ViewProvisioners/index.jsx, src/views/Provisioners/index.jsx, src/views/PulseMessages/index.jsx, src/views/Quickstart/index.jsx, src/views/Roles/ViewRoles/index.jsx, src/views/Roles/index.jsx, src/views/Scopes/ListScopes/index.jsx, src/views/Scopes/index.jsx, src/views/ScopesetExpander/index.jsx, src/views/Secrets/ViewSecret/index.jsx, src/views/Secrets/ViewSecrets/index.jsx, src/views/Secrets/index.jsx, src/views/Tasks/CreateTask/index.jsx, src/views/Tasks/NoTask/index.jsx, src/views/Tasks/NoTaskGroup/index.jsx, src/views/Tasks/TaskGroup/index.jsx, src/views/Tasks/TaskIndex/IndexedTask/index.jsx, src/views/Tasks/TaskIndex/ListNamespaces/index.jsx, src/views/Tasks/ViewTask/index.jsx, src/views/Tasks/index.jsx
=> Add each view description inside the helper view

src/components/TaskDetailsCard/index.jsx
Added style to the sourceHeadlineText
=> Changed styling and fixed icon size

.neutrinorc.js, README.md, package.json, src/App/index.jsx, src/components/Button/index.jsx, src/components/RouteWithProps/index.jsx, src/utils/prop-types.js, src/utils/withPageTracker.jsx, yarn.lock
=> Add page and event analytics

.neutrinorc.js, README.md, package.json, src/App/index.jsx, src/components/Dashboard/index.jsx, src/components/Landing/index.jsx, src/utils/reportError.js, yarn.lock
=> Report errors to sentry

src/App/index.jsx, src/utils/db.js
=> Persist dark/light theme

package.json, src/components/TaskDetailsCard/index.jsx, yarn.lock
This should help readability when viewing the task payload.
=> Deep sort task payload

package.json, src/components/Snackbar/README.md, src/components/Snackbar/index.jsx
=> Create customized snackbar component

.neutrinorc.js, netlify.toml, src/components/TaskDetailsCard/index.jsx, src/utils/urls.js, src/utils/validateActionsJson.js
=> Fix: invalid URLs

src/components/TaskRunsCard/index.jsx
=> Add link to worker ID in task run card

package.json, src/App/Main.jsx, src/App/index.jsx, src/App/routes.jsx, src/components/Dashboard/index.jsx, src/components/Landing/index.jsx, src/components/RouteWithProps/index.jsx, src/styleguide/ThemeWrapper.jsx, src/utils/Loading.jsx, src/views/AwsProvisioner/index.jsx, src/views/CachePurges/index.jsx, src/views/Clients/index.jsx, src/views/HomeOrDashboard/index.jsx, src/views/Hooks/index.jsx, src/views/Provisioners/index.jsx, src/views/Roles/index.jsx, src/views/Scopes/index.jsx, src/views/Secrets/index.jsx, src/views/Tasks/TaskIndex/index.jsx, src/views/Tasks/index.jsx, yarn.lock
=> React 16.6 enhances

src/views/ScopesetExpander/index.jsx
=> Remove highlight from scopes in scopes and make list denser

src/views/Clients/ViewClients/index.jsx
=> Fix: Pagination in clients view

src/views/Home/index.jsx
Navigation bar will appear on the home landing page for logged out users.
Fixes #196
=> add navigation bar to Landing page

src/components/Dashboard/UserMenu.jsx
=> First commit on taskcluster.Fixed the problem of username

src/components/Dashboard/UserMenu.jsx
=> Add tooltip to username

src/components/ConnectionDataTable/index.jsx
Fixes https://github.com/taskcluster/taskcluster-web/issues/213.
Regarding the issue in https://github.com/taskcluster/taskcluster-web/issues/213., searching for a new client prefix would cause an issue with the page number in `ConnectionDataTable` where page size was not being cleared away.
=> Track ConnectionDataTable page number via state

src/components/ClientScopesTable/index.jsx, src/components/ClientsTable/index.jsx, src/components/RoleScopesTable/index.jsx, src/theme.js, src/views/Scopes/ListScopes/index.jsx
An attempt to enhance performance.
Relates to #217.
=> Remove usage of animations in scopes,roles,clients

package.json, src/components/TaskDetailsCard/index.jsx, src/components/TaskRunsCard/index.jsx, yarn.lock
=> Allow text selection in list items

src/components/TaskDetailsCard/index.jsx
=> Display taskGroupId, display tags

src/components/Dashboard/SidebarListGroup.jsx, src/components/ProvisionerDetailsCard/index.jsx, src/components/TaskDetailsCard/index.jsx
=> Hide most details under  "More..."

src/components/TaskDetailsCard/index.jsx, src/theme.js
=> Display scopes and routes without overflow=scroll

src/components/Log/GoToLineButton.jsx, src/components/Log/index.jsx, src/theme.js, src/views/Tasks/LiveTaskLog/index.jsx, src/views/Tasks/TaskLog/index.jsx
=> Fix logviewer buttons when light theme

package.json, src/components/ClientScopesTable/index.jsx, src/components/RoleScopesTable/index.jsx, src/components/TaskGroupTable/index.jsx, yarn.lock
Relates to https://github.com/taskcluster/taskcluster-web/issues/217.
=> Enhance the role scopes list

src/App/index.jsx
This should speed-up page load by ~100ms :)
Fixes #271.
=> Only upgrade connection when subscriptions are used

src/components/TaskRunsCard/index.jsx
Relates to https://github.com/taskcluster/taskcluster-web/issues/252.
=> Add run number to task run card

src/components/IndexedEntry/index.jsx, src/components/TaskRunsCard/index.jsx, src/fragments/artifacts.graphql, src/utils/prop-types.js, src/views/Tasks/TaskIndex/IndexedTask/artifacts.graphql
Relates to https://github.com/taskcluster/taskcluster-web/issues/253.
=> Open logs in tc-web, otherwise open in new tab

src/components/Dashboard/index.jsx
Adjusted the height of logo in mobile view
Fixes #285
=> Fix dashboard logo height in mobile view #285

package.json, src/components/Log/index.jsx, yarn.lock
=> Logviewer extra line

src/components/Helmet/index.jsx
Images will now be properly loaded by webpack for favicon link.
Fixes #270
=> Fix favicon logo not loading #270

src/components/Dashboard/index.jsx, src/components/Landing/index.jsx
=> Fix home page horizontal scroll

src/views/Tasks/CreateTask/index.jsx
=> Disable actions when loading

.neutrinorc.js, .travis.yml, karma.conf.js, package.json, yarn.lock
Blocker: https://github.com/neutrinojs/neutrino/issues/1257
=> Bug 1491070 - Run tests in Firefox

src/components/TaskRunsCard/index.jsx
=> Show lock when url is not defined for artifacts

src/components/ClientForm/index.jsx, src/components/RoleForm/index.jsx, src/components/SecretForm/index.jsx, src/components/Shell/index.jsx, src/components/VncDisplay/index.jsx, src/views/Display/index.jsx, src/views/Tasks/CreateTask/index.jsx
#320 
Update withAlertOnClose to other pages
=> Update withAlertOnClose to Form pages.

src/views/Clients/ViewClients/index.jsx
Please kindly review and merge the PR if everything looks fine. Thanks
=> Removed the duplicate handleCreate function

src/components/Button/index.jsx, src/components/ClientForm/index.jsx, src/components/HookForm/index.jsx, src/components/Log/GoToLineButton.jsx, src/components/Log/index.jsx, src/components/RoleForm/index.jsx, src/components/SecretForm/index.jsx, src/theme.js, src/views/AwsProvisioner/ViewWorkerType/index.jsx, src/views/AwsProvisioner/ViewWorkerTypeDefinition/index.jsx, src/views/AwsProvisioner/ViewWorkerTypes/index.jsx, src/views/CachePurges/CreatePurgeCacheRequest/index.jsx, src/views/CachePurges/ViewCachePurges/index.jsx, src/views/Clients/ViewClients/index.jsx, src/views/Documentation/PageMeta.jsx, src/views/Hooks/ListHooks/index.jsx, src/views/Quickstart/index.jsx, src/views/Roles/ViewRoles/index.jsx, src/views/Scopes/ScopesetComparison/index.jsx, src/views/Scopes/ScopesetExpander/index.jsx, src/views/Secrets/ViewSecrets/index.jsx, src/views/Tasks/CreateTask/index.jsx, src/views/Tasks/LiveTaskLog/index.jsx, src/views/Tasks/TaskLog/index.jsx
=> Fix material fab variant issue

src/components/Search/index.jsx, src/views/Roles/ViewRoles/Roles.jsx
=> Remove search component console errors

src/components/Button/index.jsx, src/components/ClientForm/index.jsx, src/components/Ec2ResourcesTable/index.jsx, src/components/HookForm/index.jsx, src/components/ProvisionerDetailsCard/index.jsx, src/components/RoleForm/index.jsx, src/components/SecretForm/index.jsx, src/components/SpeedDialAction/index.jsx, src/views/AwsProvisioner/ViewWorkerType/index.jsx, src/views/AwsProvisioner/ViewWorkerTypeDefinition/index.jsx, src/views/AwsProvisioner/ViewWorkerTypes/index.jsx, src/views/CachePurges/CreatePurgeCacheRequest/index.jsx, src/views/CachePurges/ViewCachePurges/index.jsx, src/views/Hooks/ListHooks/index.jsx, src/views/Quickstart/index.jsx, src/views/Roles/ViewRoles/index.jsx, src/views/Scopes/ScopesetComparison/index.jsx, src/views/Scopes/ScopesetExpander/index.jsx, src/views/Secrets/ViewSecrets/index.jsx, src/views/Tasks/CreateTask/index.jsx, src/views/Tasks/TaskLog/index.jsx
=> "Auth Required" tooltip for disabled buttons that require auth

src/components/TaskRunsCard/index.jsx
=> Add ability to copy link from artifacts links

src/components/Log/index.jsx
=> Allow mouse wheel click and scroll vertically

src/utils/constants.js, src/views/Tasks/TaskRedirect/task.graphql, src/views/Tasks/ViewTask/task.graphql, src/views/Tasks/submitTaskAction.js
Relates to https://github.com/taskcluster/taskcluster-web-server/issues/75.
=> Rename taskGroup to decisionTask

package.json, src/components/AwsProvisionerWorkerTypeEditor/index.jsx, src/components/DialogAction/index.jsx, src/components/HookForm/index.jsx, src/components/SecretForm/index.jsx, src/views/Hooks/ListHooks/index.jsx, src/views/Hooks/ViewHook/index.jsx, yarn.lock
Fixes #365, #366.
Also fixes
* https://bugzilla.mozilla.org/show_bug.cgi?id=1509413
* https://bugzilla.mozilla.org/show_bug.cgi?id=1509412
* https://bugzilla.mozilla.org/show_bug.cgi?id=1509404
* https://bugzilla.mozilla.org/show_bug.cgi?id=1509403
=> Overall enhances to the Hooks UI

src/components/ClientForm/index.jsx, src/components/HookForm/index.jsx, src/components/RoleForm/index.jsx, src/components/SecretForm/index.jsx, src/views/Tasks/CreateTask/index.jsx
Fixes https://github.com/taskcluster/taskcluster-web/issues/375.
=> Remove warning alerts on forms

src/components/HookForm/index.jsx, src/theme.js, src/views/AwsProvisioner/ViewWorkerTypeDefinition/index.jsx, src/views/AwsProvisioner/ViewWorkerTypes/index.jsx, src/views/Quickstart/index.jsx, src/views/Tasks/CreateTask/index.jsx
Fixes https://github.com/taskcluster/taskcluster-web/issues/377.
=> Ensure action buttons sit on top (higher z-index)

src/components/ClientForm/index.jsx, src/components/RoleForm/index.jsx
Fixes https://github.com/taskcluster/taskcluster-web/issues/379.
=>  Roles: Improve readability of scopes

src/components/HookForm/index.jsx
Relates to https://github.com/taskcluster/taskcluster-web/issues/380.
=> Disable save button until all required fields are set

src/components/HookForm/index.jsx, src/views/Hooks/ViewHook/index.jsx
Fixes https://github.com/taskcluster/taskcluster-web/issues/374.
=> Refresh hook form when hooks is mutated

src/components/ClientsTable/index.jsx, src/components/RolesTable/index.jsx
Fixes https://github.com/taskcluster/taskcluster-web/issues/388.
=> Add initial sorting for roles and clients table

src/components/Helmet/index.jsx, src/utils/prop-types.js, src/views/Tasks/ViewTask/index.jsx
Fixes https://github.com/taskcluster/taskcluster-web/issues/393.
=> Show task status in favicon

src/views/Hooks/ListHooks/index.jsx
Fixes https://github.com/taskcluster/taskcluster-web/issues/373.
Relates to https://github.com/taskcluster/taskcluster-web/issues/389.
=> Expand the list of hooks when searching

src/components/TaskDetailsCard/index.jsx
Adds a Task ID list item beneath Task Group ID with a copy option. 
Fixes #360
=> Add Task ID on task screen

package.json, src/views/Hooks/ListHooks/index.jsx, yarn.lock
=> Retain search results on routing back to hooks

src/components/ClientForm/index.jsx, src/components/TaskDetailsCard/index.jsx, src/components/TaskRunsCard/index.jsx, src/components/WorkerTypesTable/index.jsx, src/components/WorkersTable/index.jsx
=> Show a tooltip when hovering on the copy icon

src/views/Quickstart/index.jsx
Fixes [bugzilla#1515673](https://bugzilla.mozilla.org/show_bug.cgi?id=1515673)
=> Updates quickstart version to 1

src/components/Button/index.jsx, src/components/WorkerTypesTable/index.jsx
Did some investigation and decided that I need to change `Button` component. I liked this one and I hope the reasoning was OK :) 
Fixes #409.
=> Fix: Worker types view modal not opening
